version: "3.4"

services:
  app:
    depends_on: [db]
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      DATABASE_TBD: connstring_goes_here_i_guess

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: fastapidbo
      POSTGRES_PASSWORD: fastapidevelopment

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080